services:
  analytics-server:
    build:
      context: .
      dockerfile: analytics_server/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - PORT=3000
      - DB_USER=webvitals
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_NAME=db
      - DB_URL=postgresql://webvitals:password@postgres:5432/db
    depends_on:
      postgres:
        condition: service_healthy
  webapp-server:
    build:
      context: .
      dockerfile: webapp_server/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - ANALYTICS_SERVER_URL=http://analytics-server:3000
      - DB_HOST=postgres
      - DB_USER=webvitals
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_NAME=db
      - DB_URL=postgresql://webvitals:password@postgres:5432/db
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=webvitals
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webvitals -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  proxy:
    build:
      context: ./webapp_client
    ports:
      - "80:80"
    depends_on:
      - analytics-server
