services:

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=webvitals
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webvitals -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

 